### PR TITLE
Fix for the stack trace issue #376.

### PR DESCRIPTION
**Pull request by yallie**

### CODE REVIEW

**Comment by dadhi** [comment]
Good, please  `[Ignore]` the test for now and I will merge and look.

**Comment by yallie** [comment]
Hi Maksim, looks like you already have a reusable hack to rethrow an exception with the real stack trace.

**Comment by yallie** [comment]
But now I'm wondering why DryIoc.Interpreter was involved here in the first place?
Is there something weird with the expression so it's not supported by FEC?

**Comment by dadhi** [comment]
Hi, thanks for the fix, will look a bit later.
Here is how current resolution pipeline working regarding the interpretation and compilation https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/ResolutionPipeline.md#resolution-pipeline

I've also understood that I need to fix ThreadSafety doc because the `lock' no more.

**Review by dadhi — APPROVED** [review]

**Comment by dadhi** [comment]
merging...

**Comment by yallie** [comment]
> Here is how current resolution pipeline working regarding the interpretation and compilation [https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/ResolutionPipeline.md#resolution-pipeline](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/ResolutionPipeline.md?rgh-link-date=2021-02-21T06%3A57%3A13Z#resolution-pipeline)

Cool! Thanks for the article, that's very interesting. 
I was unaware that DryIoc always interprets the expression on the first resolution.

**Pull request merged**
