### PR TITLE
fixes an issue where withoutFastExpression compiler option crashes wh…

### PR DESCRIPTION
**Pull request by Havunen**
fixes an issue where withoutFastExpression compiler option crashes when registeredDelegate return null value

### CODE REVIEW

**Comment by dadhi** [comment]
@havunen For know it looks fine, bu for the future this `null` looks suspicious, may be we need to inform client somehow.

**Comment by Havunen** [comment]
Ok I will change it same way its used in the other place

**Comment by Havunen** [comment]
Ok. I updated the PR. Is there anything else which is still pending for this issue to be fully resolved?

**Comment by dadhi** [comment]
Thanks, I will cleanup my stuff with the split and push the v4.2. Hoping for Today's release.

**Pull request merged**
