### PR TITLE
Reduced test case for Stackoverflow exception

### PR DESCRIPTION
**Pull request by Havunen**
I started creating reduced test case to reproduce the Stackoverflow exception https://github.com/dadhi/DryIoc/issues/139

There is new project called "ReducedStackoverflow" which is currently close to a copy of LoadTest. The idea is to remove everything what can be removed there to simplify the root cause of Stackoverflow exception. This way LoadTest can be used for performance testing in future. 

I got it this far:
Single resolve call causes the SO.
No looping, no threads.
I removed all services from this single type until I couldn't remove anything without the exception no more reproducing.

I wanted to share the progress with you if it helps finding the root cause faster.

### CODE REVIEW

**Comment by Havunen** [comment]
I can create more pull requests every time I manage to simplify it more.

**Comment by dadhi** [comment]
Great.. will look Today if time permits.

**Comment by dadhi** [comment]
Thanks. Will be merging to proceed to look to this SO

**Comment by Havunen** [comment]
It is still very complicated :-(

**Pull request merged**
