### PR TITLE
Prevent collision with Theraot.Core library

### PR DESCRIPTION
**Pull request by NN---**
https://github.com/theraot/Theraot also provides GetTypeInfo method.

### CODE REVIEW

**Review by dadhi — COMMENTED** [review]
Thanks for the PR.

But there are a lot of `GetTypeInfo` calls throughout the codebase. It would be hard to fix them all this way.

Let me think about a better way.

**Comment by NN---** [comment]
You are right. Updated the PR with new method name `GetTypeInfoUniversal`. Not sure whether it should be public or internal.

**Comment by NN---** [comment]
Btw, another solution is to rely on Theraot.Core for older frameworks if you still thinking about supporting them.

**Review by dadhi — COMMENTED** [review]
@NN--- I was also thinking about the renaming but then it will be the breaking change.

Btw, I am completely removing the GetTypeInfo in the v5 version anyway.

What is the target framework you are using it personally?

**Comment by NN---** [comment]
I wanted to use with .NET 4.
I also use Theraot for backporting new features.
Mixing together is a problem as you can see.

Right now I solved it manually by editing the file.

There is still issue with async context , I am investigating how to solve it. The problem is that async/await was not supported natively in .NET 4.0.

**Comment by NN---** [comment]
I understand that .NET 4.0 support is not part of DryIoc 5, right ?

**Comment by dadhi** [comment]
> I understand that .NET 4.0 support is not part of DryIoc 5, right ?

Yes, that's why I was asking.

**Comment by NN---** [comment]
Can you see if you are able to build for .NET 4 without any change using Theraot library backport?

**Comment by dadhi** [comment]
> Theraot library backport
 What do you mean by backport?

**Comment by NN---** [comment]
I mean it provides some compatibility layer to make code for newer frameworks work with older ones.
It is not always 100% without code change due to some limitations like lack of extension properties, but mostly using very small adaptions.

**Comment by dadhi** [comment]
Outdated.

**Pull request closed without merging**
